services:
  postgres:
    image: postgres:16
    container_name: postgres
    networks:
      hudi_net:
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
  spark-runner:
    image: apache/spark:3.5.2
    container_name: spark-runner
    depends_on:
      - minio
      - hive-metastore
      - mc
    networks:
      hudi_net:
    volumes:
      - ./.ivy2:/home/spark/.ivy2
      - ./.m2:/home/spark/.m2
      - ./spark-conf:/opt/spark/conf
      - ./hudi-sql:/init:ro
      - ./parquet_data:/parquet_data:ro
    environment:
      HMS_URI: thrift://hive-metastore:9083
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    command: >
      bash -lc '/opt/spark/bin/spark-sql -f /init/init.sql'
  hive-metastore:
    image: apache/hive:4.0.0
    container_name: hive-metastore
    networks:
      hudi_net:
    depends_on:
      - minio
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      hudi_net:
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      hudi_net:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc anonymous set public minio/warehouse;
      tail -f /dev/null
      "
  spark:
    image: apache/spark:3.5.2
    container_name: spark
    depends_on:
      - hive-metastore
      - minio
    volumes:
      - ./.ivy2:/home/spark/.ivy2
      - ./.m2:/home/spark/.m2
      - ./spark-conf:/opt/spark/conf
      - ./hudi-sql:/init:ro
      - ./parquet_data:/parquet_data:ro
    environment:
      HMS_URI: thrift://hive-metastore:9083
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    command: ["bash","-lc","tail -f /dev/null"]
  puppygraph:
    image: puppygraph/puppygraph:stable
    container_name: puppygraph
    networks:
      hudi_net:
    environment:
      - PUPPYGRAPH_USERNAME=puppygraph
      - PUPPYGRAPH_PASSWORD=puppygraph123
    ports:
      - "8081:8081"
      - "8182:8182"
      - "7687:7687"
networks:
  hudi_net:
    name: puppy-hudi