networks:
  hudi_net: {}

volumes:
  pgdata:
  minio-data:

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: metastore
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d metastore"]
      interval: 3s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [hudi_net]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console
    volumes:
      - minio-data:/data
    networks: [hudi_net]

  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    networks: [hudi_net]
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 admin password; do sleep 1; done;
      mc mb -p local/warehouse || true;
      mc anonymous set none local/warehouse || true;
      "

  metastore:
    image: apache/hive:4.0.0
    depends_on:
      postgres:
        condition: service_healthy
    networks: [hudi_net]
    # Mount the Postgres JDBC driver (downloaded on the host)
    volumes:
      - ./jars/postgresql-42.7.3.jar:/opt/hive/lib/postgresql-42.7.3.jar:ro
    restart: unless-stopped
    # Initialize schema (idempotent) then run HMS in the foreground (exec)
    command: >
      bash -lc '
        schematool -dbType postgres -initSchema --verbose
          --hiveconf javax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore
          --hiveconf javax.jdo.option.ConnectionDriverName=org.postgresql.Driver
          --hiveconf javax.jdo.option.ConnectionUserName=postgres
          --hiveconf javax.jdo.option.ConnectionPassword=postgres123
          || true;
        exec /opt/hive/bin/hive --service metastore -p 9083
          --hiveconf javax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore
          --hiveconf javax.jdo.option.ConnectionDriverName=org.postgresql.Driver
          --hiveconf javax.jdo.option.ConnectionUserName=postgres
          --hiveconf javax.jdo.option.ConnectionPassword=postgres123
      '
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'exec 3<>/dev/tcp/127.0.0.1/9083'"]
      interval: 5s
      timeout: 3s
      retries: 40

  spark:
    image: apache/spark:3.5.1-scala2.12-java17-ubuntu
    depends_on:
      - metastore
      - minio
    networks: [hudi_net]
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
    volumes:
      - ./spark-conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
      - ./init.sql:/init.sql:ro               # optional, if you have it
      - ./parquet_data:/parquet_data:ro       # optional, if you have data
    command: ["bash", "-lc", "tail -f /dev/null"]  # keep container ready for exec

  puppygraph:
    image: puppygraph/puppygraph:stable
    depends_on:
      - metastore
      - minio
    environment:
      PUPPYGRAPH_USERNAME: puppygraph
      PUPPYGRAPH_PASSWORD: puppygraph123
    ports:
      - "8081:8081"  # Web UI
      - "8182:8182"  # Gremlin
      - "7687:7687"  # Bolt
    networks: [hudi_net]
